import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../src/components/Header'
import Card from '../src/components/Card'
import Grid from '@material-ui/core/Grid'
import { makeStyles } from '@material-ui/core/styles'
import { Container, Typography } from '@material-ui/core'
const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
    justifyContent: 'center'
  },
  paper: {
    height: 140,
    width: 100,
  },
  control: {
    padding: theme.spacing(2),
  },
  title: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '10.6rem',
  },
  titleS: {
    border: '5px black solid',
    borderTop: '2px',
    borderLeft: '2px',
    padding: '10px',
    borderColor: '#5187b6',
    borderRadius: '5px'
  },
}));

export default function Home() {
  const classes = useStyles();

  return (
    <div className={styles.container}>
      <Head>
        <title>Pousada Sol do Rosa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <Header />

      <main className={styles.main}>
        <Container maxWidth={'lg'}>
          <Typography variant="h1" component="div" className={classes.title}>
            Pousada
            <p className={classes.titleS}> Sol do Rosa </p>
          </Typography>
        </Container>

        <Grid container className={classes.root} spacing={2}>
          <Grid item md={4}>
            <Card title={"Quarto 1"} />
          </Grid>

          <Grid item md={4}>
            <Card title={"Quarto 2"} />
          </Grid>

          <Grid item md={4}>
            <Card title={"Quarto 3"} />
          </Grid>

          <Grid item md={4}>
            <Card title={"Quarto 4"} />
          </Grid>

          <Grid item md={4}>
            <Card title={"Quarto 5"} />
          </Grid>
          <Grid item md={4}>
            <Card title={"Quarto 6"} />
          </Grid>

          <Grid item md={4}>
            <Card title={"Quarto 7"} />
          </Grid>

          <Grid item md={4}>
            <Card title={"Quarto 8"} />
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
